---
title: "Descriptives"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(haven)
```

```{r data}

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
df <- read_dta("dataverse_files/AER merged.dta")
df <- na.omit(df)

df$gave <- ifelse(df$gave == 1, "Gave", "Did not give")

treated <- df %>% filter(treatment == 1)
control <- df %>% filter(treatment == 0)

df_nonzero <- df %>% filter(amount !=0)
treated_nonzero <- df %>% filter(amount !=0, treatment == 1)
control_nonzero <- df %>% filter(amount !=0, treatment == 0)

```

```{r treatment}

# Treatment vs. control --------------------------------------------------------
treatment_txt <- ifelse(df$treatment == 1, "Treatment", "Control")
treatment_txt_nonzero <- ifelse(df_nonzero$treatment == 1, "Treatment", "Control")

ggplot(data=df, aes(amount, fill=treatment_txt, color=treatment_txt)) + 
  geom_density(position="stack", alpha=1) + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by treament vs. control") + 
  scale_fill_discrete("") + 
  scale_color_discrete("")

ggplot(data=df_nonzero, aes(amount, fill=treatment_txt_nonzero, color=treatment_txt_nonzero)) + 
  geom_density(position="stack", alpha=1) + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by treament vs. control", 
       subtitle="For non-zero amounts given") + 
  scale_fill_discrete("") + 
  scale_color_discrete("")

ggplot(data=df, aes(gave, fill=treatment_txt)) + 
  geom_bar(position="stack", alpha=1) + 
  labs(x="Did the subject give any amount?", 
       y="Frequency", 
       title="Giving by treatment vs. control") + 
  scale_fill_discrete("")

```


```{r ratio}
# Ratio ------------------------------------------------------------------------
ratio_txt <- ifelse(df$ratio ==0, "Control", ifelse(df$ratio == 1, "1:1", ifelse(df$ratio == 2, "2:1", "3:1")))
ratio_txt_nonzero <- ifelse(df_nonzero$ratio ==0, "Control", ifelse(df_nonzero$ratio == 1, "1:1", ifelse(df_nonzero$ratio == 2, "2:1", "3:1")))

ggplot(data=df, aes(amount, fill=ratio_txt, color=ratio_txt)) + 
  geom_density(position="stack") + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by match ratio") + 
  scale_fill_discrete("Match ratio") + 
  scale_color_discrete("Match ratio")

ggplot(data=df_nonzero, aes(amount, fill=ratio_txt_nonzero, color=ratio_txt_nonzero)) + 
  geom_density(position="stack") + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by match ratio", 
       subtitle="For non-zero amounts given") + 
  scale_fill_discrete("Match ratio") + 
  scale_color_discrete("Match ratio")

ggplot(data=df, aes(gave, fill=ratio_txt)) + 
  geom_bar(position="stack") + 
  labs(x="Did the subject give any amount?", 
       y="Frequency", 
       title="Giving by match ratio") + 
  scale_fill_discrete("Match ratio")

```


```{r threshold}
# Threshold --------------------------------------------------------------------
thres_txt <- ifelse(df$size ==0, "Control", ifelse(df$size == 1, "$25,000", ifelse(df$size == 2, "$50,000", ifelse(df$size ==3, "$100,000", "Unstated"))))
thres_txt_nonzero <- ifelse(df_nonzero$size ==0, "Control", ifelse(df_nonzero$size == 1, "$25,000", ifelse(df_nonzero$size == 2, "$50,000", ifelse(df_nonzero$size ==3, "$100,000", "Unstated"))))

ggplot(data=df, aes(amount, fill=thres_txt, color=thres_txt)) + 
  geom_density(position="stack") + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by threshold") + 
  scale_fill_discrete("Threshold") + 
  scale_color_discrete("Threshold")

ggplot(data=df_nonzero, aes(amount, fill=thres_txt_nonzero, color=thres_txt_nonzero)) + 
  geom_density(position="stack") + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by threshold", 
       subtitle="For non-zero amounts given") + 
  scale_fill_discrete("Threshold") + 
  scale_color_discrete("Threshold")

ggplot(data=df, aes(gave, fill=thres_txt)) + 
  geom_bar(position="stack") + 
  labs(x="Did the subject give any amount?", 
       y="Frequency", 
       title="Giving by threshold") + 
  scale_fill_discrete("Threshold")

```


```{r example}

# Example ----------------------------------------------------------------------
ask_txt <- ifelse(df$ask==0, "Control", ifelse(df$ask == 1, "Low", ifelse(df$ask == 2, "Medium", "High")))
ask_txt_nonzero <- ifelse(df_nonzero$ask==0, "Control", ifelse(df_nonzero$ask == 1, "Low", ifelse(df_nonzero$ask == 2, "Medium", "High")))

ggplot(data=df, aes(amount, fill=ask_txt, color=ask_txt)) + 
  geom_density(position="stack", alpha=1) + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by example amount") + 
  scale_fill_discrete("Example amount") + 
  scale_color_discrete("Example amount")

ggplot(data=df_nonzero, aes(amount, fill=ask_txt_nonzero, color=ask_txt_nonzero)) + 
  geom_density(position="stack", alpha=1) + 
  labs(x="Amount given (dollars)", 
       y="Density", 
       title="Amount by example amount", 
       subtitle="For non-zero amounts given") + 
  scale_fill_discrete("Example amount") + 
  scale_color_discrete("Example amount")

ggplot(data=df, aes(gave, fill=ask_txt)) + 
  geom_bar(position="stack", alpha=1) + 
  labs(x="Did the subject give any amount?", 
       y="Frequency", 
       title="Giving by example amount") + 
  scale_fill_discrete("Example amount")


```

