---
title: "Neyman"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(haven)
```

```{r data}

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
df <- read_dta("dataverse_files/AER merged.dta")
df <- na.omit(df)

treated <- df %>% filter(treatment == 1)
control <- df %>% filter(treatment == 0)

```

```{r neyman}

# Input: Two treatment groups
# Function that returns: 
#   (1) difference in means estimator
#   (2) estimate of variance
#   (3) p-value as a list 
neyman <- function(Y1, Y0){
  est <- mean(Y1) - mean(Y0)
  
  n1 <- length(Y1)
  n0 <- length(Y0)
  var1 <- var(Y1)
  var0 <- var(Y0)
  est_var <- var1/n1 + var0/n0
  
  pval <- 2 * pnorm(abs(est/sqrt(est_var)), lower.tail=FALSE)
  out <- list("est" = est, "se" = sqrt(est_var), "p" = pval)
  
  return(out)
}

```

\newpage
# Outcome: amount 

```{r amount}

# Treatment vs. control --------------------------------------------------------

neyman(treated$amount, control$amount)

# Match ratio ------------------------------------------------------------------

## 1:1 
neyman(treated$amount[treated$ratio == 1], control$amount)

## 2:1 
neyman(treated$amount[treated$ratio == 2], control$amount)

## 3:1
neyman(treated$amount[treated$ratio == 3], control$amount)

# Threshold --------------------------------------------------------------------

## $25k 
neyman(treated$amount[treated$size == 1], control$amount)

## $50k 
neyman(treated$amount[treated$size == 2], control$amount)

## $100k
neyman(treated$amount[treated$size == 3], control$amount)

# Example amount ---------------------------------------------------------------

# Low 
neyman(treated$amount[treated$ask == 1], control$amount)

# Med
neyman(treated$amount[treated$ask == 2], control$amount)

# High
neyman(treated$amount[treated$ask == 3], control$amount)

```

## Covariates 

```{r covariates-amount}

# Blue vs. red -----------------------------------------------------------------

# Blue 
neyman(treated$amount[treated$blue0==1], control$amount[control$blue0==1])

# Red 
neyman(treated$amount[treated$red0==1], control$amount[control$red0==1])

# Donated in 2005 --------------------------------------------------------------

# Donated 
neyman(treated$amount[treated$dormant==1], control$amount[control$dormant==1])

# Did not donate 
neyman(treated$amount[treated$dormant==0], control$amount[control$dormant==0])

```

\newpage 
# Outcome: gave

```{r gave}

# Treatment vs. control --------------------------------------------------------

neyman(treated$gave, control$gave)

# Match ratio ------------------------------------------------------------------

## 1:1 
neyman(treated$gave[treated$ratio == 1], control$gave)

## 2:1 
neyman(treated$gave[treated$ratio == 2], control$gave)

## 3:1
neyman(treated$gave[treated$ratio == 3], control$gave)

# Threshold --------------------------------------------------------------------

## $25k 
neyman(treated$gave[treated$size == 1], control$gave)

## $50k 
neyman(treated$gave[treated$size == 2], control$gave)

## $100k
neyman(treated$gave[treated$size == 3], control$gave)

# Example amount ---------------------------------------------------------------

# Low 
neyman(treated$gave[treated$ask == 1], control$gave)

# Med
neyman(treated$gave[treated$ask == 2], control$gave)

# High
neyman(treated$gave[treated$ask == 3], control$gave)

```

## Covariates 

```{r covariates-gave}

# Blue vs. red -----------------------------------------------------------------

# Blue 
neyman(treated$gave[treated$blue0==1], control$gave[control$blue0==1])

# Red 
neyman(treated$gave[treated$red0==1], control$gave[control$red0==1])

# Donated in 2005 --------------------------------------------------------------

# Donated 
neyman(treated$gave[treated$dormant==1], control$gave[control$dormant==1])

# Did not donate 
neyman(treated$gave[treated$dormant==0], control$gave[control$dormant==0])

```



